<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMwC78Cu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMwC78Cu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMwC78Cu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMwC78Cu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMwC78Cu\App_KernelDevDebugContainer([
    'container.build_hash' => 'MwC78Cu',
    'container.build_id' => '1ec75406',
    'container.build_time' => 1613360781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMwC78Cu');
