<?php

namespace Container75cvfFG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7fAUu8oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7fAUu8o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7fAUu8o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AppointmentController::delete' => ['privates', '.service_locator.CJm3vPx', 'get_ServiceLocator_CJm3vPxService', true],
            'App\\Controller\\AppointmentController::edit' => ['privates', '.service_locator.CJm3vPx', 'get_ServiceLocator_CJm3vPxService', true],
            'App\\Controller\\AppointmentController::index' => ['privates', '.service_locator.5FrqsYh', 'get_ServiceLocator_5FrqsYhService', true],
            'App\\Controller\\CustomerController::delete' => ['privates', '.service_locator.VaFcGWn', 'get_ServiceLocator_VaFcGWnService', true],
            'App\\Controller\\CustomerController::edit' => ['privates', '.service_locator.VaFcGWn', 'get_ServiceLocator_VaFcGWnService', true],
            'App\\Controller\\CustomerController::index' => ['privates', '.service_locator.IUmGxgb', 'get_ServiceLocator_IUmGxgbService', true],
            'App\\Controller\\CustomerController::show' => ['privates', '.service_locator.VaFcGWn', 'get_ServiceLocator_VaFcGWnService', true],
            'App\\Controller\\PlaceController::index' => ['privates', '.service_locator.PjAOekm', 'get_ServiceLocator_PjAOekmService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AppointmentController:delete' => ['privates', '.service_locator.CJm3vPx', 'get_ServiceLocator_CJm3vPxService', true],
            'App\\Controller\\AppointmentController:edit' => ['privates', '.service_locator.CJm3vPx', 'get_ServiceLocator_CJm3vPxService', true],
            'App\\Controller\\AppointmentController:index' => ['privates', '.service_locator.5FrqsYh', 'get_ServiceLocator_5FrqsYhService', true],
            'App\\Controller\\CustomerController:delete' => ['privates', '.service_locator.VaFcGWn', 'get_ServiceLocator_VaFcGWnService', true],
            'App\\Controller\\CustomerController:edit' => ['privates', '.service_locator.VaFcGWn', 'get_ServiceLocator_VaFcGWnService', true],
            'App\\Controller\\CustomerController:index' => ['privates', '.service_locator.IUmGxgb', 'get_ServiceLocator_IUmGxgbService', true],
            'App\\Controller\\CustomerController:show' => ['privates', '.service_locator.VaFcGWn', 'get_ServiceLocator_VaFcGWnService', true],
            'App\\Controller\\PlaceController:index' => ['privates', '.service_locator.PjAOekm', 'get_ServiceLocator_PjAOekmService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AppointmentController::delete' => '?',
            'App\\Controller\\AppointmentController::edit' => '?',
            'App\\Controller\\AppointmentController::index' => '?',
            'App\\Controller\\CustomerController::delete' => '?',
            'App\\Controller\\CustomerController::edit' => '?',
            'App\\Controller\\CustomerController::index' => '?',
            'App\\Controller\\CustomerController::show' => '?',
            'App\\Controller\\PlaceController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AppointmentController:delete' => '?',
            'App\\Controller\\AppointmentController:edit' => '?',
            'App\\Controller\\AppointmentController:index' => '?',
            'App\\Controller\\CustomerController:delete' => '?',
            'App\\Controller\\CustomerController:edit' => '?',
            'App\\Controller\\CustomerController:index' => '?',
            'App\\Controller\\CustomerController:show' => '?',
            'App\\Controller\\PlaceController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
